CLUSTER_REGION="asia-east1"
CLUSTER_ZONE="asia-east1-a"

CLUSTER_NAME="c1"
ETCD_PORT=4001
APISERVER_PORT=6443
APISERVER_INSECURE_PORT=8888
DOCKER_IN_DOCKER_WORK_DIR="${DOCKER_IN_DOCKER_WORK_DIR}/${CLUSTER_NAME}"
