CLUSTER_REGION="asia-west2"
CLUSTER_ZONE="asia-west2-b"

CLUSTER_NAME="c2"
ETCD_PORT=4101
APISERVER_PORT=6543
APISERVER_INSECURE_PORT=9999
DOCKER_IN_DOCKER_WORK_DIR="${DOCKER_IN_DOCKER_WORK_DIR}/${CLUSTER_NAME}"
